export const CATEGORIES = [
  { id: 'all',         label: 'Tout',          icon: '🏪' },
  { id: 'electronics', label: 'Électronique',  icon: '📱' },
  { id: 'auto',        label: 'Auto',          icon: '🚗' },
  { id: 'home',        label: 'Maison',        icon: '🛋️' },
  { id: 'fashion',     label: 'Mode',          icon: '👗' },
  { id: 'sport',       label: 'Sport',         icon: '⚽' },
  { id: 'kids',        label: 'Enfant',        icon: '🧸' },
]

export const LISTINGS = [
  {
    id: 1,
    title: 'iPhone 14 Pro 256Go',
    price: 285000,
    category: 'electronics',
    city: 'Cotonou',
    emoji: '📱',
    condition: 'Très bon état',
    seller: { id: 1, name: 'Kofi Mensah', avatar: 'K', rating: 4.9, memberSince: 'Jan 2024' },
    description: "iPhone 14 Pro en excellent état, batterie à 96%. Vendu avec chargeur original et coque. Achat en janvier 2024. Aucune rayure, fonctionne parfaitement.",
    images: ['📱', '🔋', '📦'],
    isNew: true,
    createdAt: '2025-01-15',
  },
  {
    id: 2,
    title: 'Toyota Corolla 2019',
    price: 7500000,
    category: 'auto',
    city: 'Cotonou',
    emoji: '🚗',
    condition: 'Bon état',
    seller: { id: 2, name: 'Ama Touré', avatar: 'A', rating: 4.7, memberSince: 'Mars 2023' },
    description: "Corolla en très bon état, entretien régulier chez concessionnaire, première main. Climatisation fonctionnelle. Carnet d'entretien disponible.",
    images: ['🚗', '🪑', '⚙️'],
    isNew: false,
    createdAt: '2025-01-10',
  },
  {
    id: 3,
    title: 'Canapé 3 places cuir',
    price: 95000,
    category: 'home',
    city: 'Porto-Novo',
    emoji: '🛋️',
    condition: 'Bon état',
    seller: { id: 3, name: 'Jean Picard', avatar: 'J', rating: 4.5, memberSince: 'Juin 2023' },
    description: "Canapé cuir beige 3 places, utilisé 1 an. Très confortable, aucune déchirure. Vendu car déménagement.",
    images: ['🛋️', '🏠'],
    isNew: false,
    createdAt: '2025-01-08',
  },
  {
    id: 4,
    title: 'Nike Air Max 270 — Taille 42',
    price: 45000,
    category: 'fashion',
    city: 'Cotonou',
    emoji: '👟',
    condition: 'Neuf',
    seller: { id: 4, name: 'Grace Koffi', avatar: 'G', rating: 5.0, memberSince: 'Déc 2024' },
    description: "Nike Air Max 270 neuves, jamais portées, emballage d'origine. Taille 42 EU. Achetées à Paris.",
    images: ['👟', '📦'],
    isNew: true,
    createdAt: '2025-01-14',
  },
  {
    id: 5,
    title: 'MacBook Air M2 8Go/256Go',
    price: 620000,
    category: 'electronics',
    city: 'Parakou',
    emoji: '💻',
    condition: 'Très bon état',
    seller: { id: 5, name: 'Ali Bamba', avatar: 'A', rating: 4.8, memberSince: 'Fév 2024' },
    description: "MacBook Air M2 2023, 8Go RAM, 256Go SSD. Parfait état, peu utilisé. Vendu avec chargeur MagSafe.",
    images: ['💻', '🔌'],
    isNew: false,
    createdAt: '2025-01-12',
  },
  {
    id: 6,
    title: 'VTT 26" — 21 vitesses',
    price: 75000,
    category: 'sport',
    city: 'Cotonou',
    emoji: '🚴',
    condition: 'Bon état',
    seller: { id: 6, name: 'Marc Loko', avatar: 'M', rating: 4.6, memberSince: 'Août 2023' },
    description: "VTT adulte 26 pouces, 21 vitesses Shimano, freins disque. Pneus neufs. Révision complète faite.",
    images: ['🚴', '🔧'],
    isNew: false,
    createdAt: '2025-01-09',
  },
  {
    id: 7,
    title: 'Machine à laver Samsung 7kg',
    price: 185000,
    category: 'home',
    city: 'Abomey-Calavi',
    emoji: '🫧',
    condition: 'Très bon état',
    seller: { id: 7, name: 'Fatou Diallo', avatar: 'F', rating: 4.9, memberSince: 'Mai 2023' },
    description: "Lave-linge Samsung 7kg, classe A++, 8 programmes. Fonctionne parfaitement, vendu car achat d'un modèle plus grand.",
    images: ['🫧', '📋'],
    isNew: false,
    createdAt: '2025-01-07',
  },
  {
    id: 8,
    title: 'Ensemble Ankara 2 pièces',
    price: 18000,
    category: 'fashion',
    city: 'Cotonou',
    emoji: '👗',
    condition: 'Neuf',
    seller: { id: 8, name: 'Adjoa Nana', avatar: 'A', rating: 4.8, memberSince: 'Nov 2024' },
    description: "Ensemble Ankara taille 40, couleurs vives, jamais porté. Couture locale de qualité.",
    images: ['👗'],
    isNew: true,
    createdAt: '2025-01-13',
  },
]

export const CONVERSATIONS = [
  {
    id: 1,
    participant: { name: 'Kofi Mensah', avatar: 'K', color: 'bg-brand-500' },
    listing: 'iPhone 14 Pro — 285 000 FCFA',
    messages: [
      { id: 1, from: 'them', text: "Bonjour, l'iPhone est encore disponible ?", time: '14:20' },
      { id: 2, from: 'me', text: "Oui toujours ! Tu es à Cotonou ?", time: '14:22' },
      { id: 3, from: 'them', text: "Oui je suis à Cadjehoun. On peut se voir demain ?", time: '14:25' },
      { id: 4, from: 'me', text: "Pas de problème, disons vers 10h au marché Dantokpa ?", time: '14:30' },
      { id: 5, from: 'them', text: "C'est encore disponible ?", time: '14:32' },
    ],
    unread: true,
    lastTime: '14:32',
  },
  {
    id: 2,
    participant: { name: 'Ama Touré', avatar: 'A', color: 'bg-green-500' },
    listing: 'Canapé 3 places — 95 000 FCFA',
    messages: [
      { id: 1, from: 'them', text: "Est-ce que vous livrez ?", time: 'Hier' },
      { id: 2, from: 'me', text: "Oui pour Cotonou, 2000 FCFA de frais.", time: 'Hier' },
      { id: 3, from: 'them', text: "Merci, livraison demain ✓", time: 'Hier' },
    ],
    unread: false,
    lastTime: 'Hier',
  },
  {
    id: 3,
    participant: { name: 'Sébastien Rocha', avatar: 'S', color: 'bg-blue-500' },
    listing: 'Nike Air Max 270 — 45 000 FCFA',
    messages: [
      { id: 1, from: 'them', text: "Salut, tu peux baisser à 40 000 ?", time: 'Lun.' },
      { id: 2, from: 'me', text: "Minimum 43 000, elles sont neuves.", time: 'Lun.' },
      { id: 3, from: 'them', text: "Tu peux baisser à 45 000 ?", time: 'Lun.' },
    ],
    unread: false,
    lastTime: 'Lun.',
  },
]
